#
# k8s-cms
# Kubernetes Intergration
# Helm Chart
# 

# chart metadata 
apiVersion: v2
appVersion: "1.4.rc1"
type: application
name: k8s-cms
description: Chart to deploy Contest Managment System on Kubernetes.
version: 0.3.0
sources:
- "https://github.com/mrzzy/cms.git"
- "https://github.com/cms-dev/con_test.git"
- "https://github.com/vishnubob/wait-for-it.git"

# chart dependencies
dependencies:
- name: nginx-ingress
  version: 1.28.2
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: nginx-ingress.enabled
- name: cert-manager
  version: 0.12.0
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
- name: prometheus-operator
  version: 6.14.2
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: prometheus-operator.enabled
