#
# k8s-cms
# Docker Compose 
# 

version: '3'
services:
  cms-db:
    build: 
      context: .
      dockerfile: containers/cms-db/Dockerfile
    image: mrzzy/cms-db
    expose:
    - "5432"
    env_file: .env
    environment:
      - CMS_DB=localhost
  cms-web-admin:
    build: 
      context: .
      dockerfile: containers/cms-web-admin/Dockerfile
    image: mrzzy/cms-web-admin
    ports:
      - "8889:8889"
    expose:
      - "21100"
    env_file: .env
    depends_on:
      - cms-db
      - cms-log
  cms-log:
    build: 
      context: .
      dockerfile: containers/cms-log/Dockerfile
    image: mrzzy/cms-log
    env_file: .env
    expose:
      - "29000"
    depends_on:
      - cms-db
  cms-scoring:
    build: 
      context: .
      dockerfile: containers/cms-scoring/Dockerfile
    image: mrzzy/cms-scoring
    env_file: .env
    expose:
      - "28500"
    depends_on:
      - cms-db
      - cms-log
  
