#
# k8s-cms
# Kubernetes Intergration
#

namespace: k8s-cms
commonLabels:
  app: k8s-cms
  version: 0.2.0a
  release: rolling
  envionment: dev

configMapGenerator:
  - name: cms-config-env
    env: "config/config.env"
  - name: cms-config
    files:
      - "config/cms.conf"
      - "config/cms.ranking.conf"
      - "config/nginx.conf"
    
secretGenerator:
  - name: cms-secrets
    env: ".env"

resources:
  - "k8s/namespace.yml"

  # database
  - "k8s/deployments/database.yml"
  - "k8s/services/database.yml"
  - "k8s/storage/database-data.yml"

  # cms resources service
  - "k8s/deployments/cms-resources.yml"
  - "k8s/services/cms-resources.yml"
    
  # cms logging service
  - "k8s/deployments/cms-logging.yml"
  - "k8s/services/cms-logging.yml"
   
  # cms scoring service
  - "k8s/deployments/cms-scoring.yml"
  - "k8s/services/cms-scoring.yml"
    
  # cms evaluation service
  - "k8s/deployments/cms-evaluation.yml"
  - "k8s/services/cms-evaluation.yml"

  # cms proxy service  
  - "k8s/deployments/cms-proxy.yml"
  - "k8s/services/cms-proxy.yml"
    
  # cms web admin interface
  - "k8s/deployments/cms-web-admin.yml"
  - "k8s/services/cms-web-admin.yml"

  # cms web printing interface
  - "k8s/deployments/cms-printing.yml"
  - "k8s/services/cms-printing.yml"


patchesStrategicMerge:
  - "k8s/config.yaml"
