#
# k8s-cms
# Kubernetes Intergration
# Helm Chart Dependencies
# 

dependencies:
  - name: nginx-ingress
    version: 1.24.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: nginx-ingress.enabled
