#
# k8s-cms
# Kubernetes Intergration
# CMS Resources Deployment
#

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "k8s-cms.fullname" . }}-resources
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: resources
spec:
  selector:
    matchLabels:
{{ include "k8s-cms.labels" . | indent 6 }}
      component: resources
  template:
    metadata:
      labels:
{{ include "k8s-cms.labels" . | indent 8 }}
        component: resources
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ .Values.security.serviceAccount.name }}
      containers:
        {{- with .Values.images.resources }}
        - name: {{ .name }}
          image: {{ .repository }}:{{ .tag }}
        {{- end }}
          ports:
            - name: cmsres
              containerPort: 28000
          envFrom:
            - configMapRef:
              name: {{ include "k8s-cms.fullname" . }}-config-env
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cms-secrets
                  key: POSTGRES_PASSWORD
            # required for container to listen
            - name: CMS_RESOURCE
              value: "0.0.0.0"
          livenessProbe:
            tcpSocket:
              port: cmsres
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: cmsres
            periodSeconds: 3

          volumeMounts:
            - name: {{ include "k8s-cms.fullname" . }}-config-file
              mountPath: "/cms/config"
      volumes:
        - name: {{ include "k8s-cms.fullname" . }}-config
          configMap:
            name: {{ include "k8s-cms.fullname" . }}-config-file
