#
# k8s-cms
# Kubernetes Intergration
#

namespace: k8s-cms
commonLabels:
  app: k8s-cms
  version: 0.2.0a
  release: rolling
  envionment: dev

resources:
  - namespace.yml

  # database
  - deployments/database.yml
  - services/database.yml
