#
# k8s-cms
# Kubernetes Intergration
# CMS Worker Service
#

apiVersion: v1
kind: Service
metadata:
  name: cms-worker
  labels:
    app: k8s-cms
    component: worker
spec:
  # define worker service as headless
  clusterIP: None 
  selector:
    app: k8s-cms
    component: worker
  ports:
    - name: cmswork
      port: 26000
      targetPort: 26000
