#
# k8s-cms
# Kubernetes Intergration
# CMS Printing Service
#

apiVersion: v1
kind: Service
metadata:
  name: cms-printing
  labels:
    app: k8s-cms
    component: printing
spec:
  type: ClusterIP
  selector:
    app: k8s-cms
    component: printing
  ports:
    # port used by service communication
    - name: cmsprint
      port: 25123
      targetPort: 25123
