#
# k8s-cms
# Kubernetes Intergration
# CMS Checker Service
#

apiVersion: v1
kind: Service
metadata:
  name: cms-checker
  labels:
    app: k8s-cms
    component: checker
spec:
  type: ClusterIP
  selector:
    app: k8s-cms
    component: checker
  ports:
    - name: cmscheck
      port: 22000
      targetPort: 22000
