#
# k8s-cms
# Kubernetes Intergration
# CMS Proxy Service
#

apiVersion: v1
kind: Service
metadata:
  name: cms-proxy
  labels:
    app: k8s-cms
    component: proxy
spec:
  type: ClusterIP
  selector:
    app: k8s-cms
    component: proxy
  ports:
    - name: cmsproxy
      port: 28600
      targetPort: 28600

