#
# k8s-cms
# Kubernetes Intergration
# Database Data Storage
#

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-cms.fullname" . }}-database-data-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
