#
# k8s-cms
# Kubernetes Intergration
# CMS Workers Deployment
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cms-worker
  labels:
    app: k8s-cms
    component: worker
spec:
  serviceName: cms-worker
  podManagementPolicy: Parallel
  replicas: 6
  selector:
    matchLabels:
      app: k8s-cms
      component: worker
  template:
    metadata:
      labels:
        app: k8s-cms
        component: worker
    spec:
      containers:
        - name: cms-worker
          image: mrzzy/cms-worker
          imagePullPolicy: IfNotPresent
          ports:
            - name: cmswork
              containerPort: 26000
          envFrom:
            - configMapRef:
                name: cms-config-env
            - configMapRef:
                name: cms-config-worker-env
            - secretRef:
                name: cms-secrets
          env:
            # required for container to listen
            - name: CMS_RESOURCE
              value: "0.0.0.0"
            - name: CMS_WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            tcpSocket:
              port: cmswork
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: cmswork
            periodSeconds: 3
          securityContext:
            privileged: true
          volumeMounts:
            - name: cms-config
              mountPath: "/cms/config"
      volumes:
        - name: cms-config
          configMap:
            name: cms-config
      terminationGracePeriodSeconds: 5
  volumeClaimTemplates: []
