#
# k8s-cms
# Kubernetes Intergration
# k8s-cms Master 
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.master.name }}
  labels:
{{ include "k8s-cms.labels" . | indent 4 }}
    component: master
spec:
  type: {{ .Values.services.master.type }}
  selector:
{{ include "k8s-cms.selectors" . | indent 4 }}
    component: master
  ports:
    - name: http
      port: 80
      targetPort: 5000
