#
# k8s-cms
# Kubenetes Intergration
# Ingress
# 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "k8s-cms.fullname" . }}-web
  labels:
    app: k8s-cms
spec:
  rules:
    - host: k8s-cms.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: cms-web-contest
              servicePort: 80
    - host: admin.k8s-cms.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: cms-web-admin
              servicePort: 80
    - host: ranking.k8s-cms.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: cms-web-ranking
              servicePort: 80
