#
# k8s-cms
# Kubernetes Intergration
# CMS Resources Service
#

apiVersion: v1
kind: Service
metadata:
  name: cms-resources
  labels:
    app: k8s-cms
    component: resources
spec:
  type: ClusterIP
  selector:
    app: k8s-cms
    component: resources
  ports:
    - name: cmsres
      port: 28000
      targetPort: 28000
