#
# k8s-cms
# Kubernetes Intergration
# CMS Admin Service
#

apiVersion: v1
kind: Service
metadata:
  name: cms-admin
  labels:
    app: k8s-cms
    component: admin
spec:
  type: ClusterIP
  selector:
    app: k8s-cms
    component: admin
  ports:
    - name: cmsadmin
      port: 21100
      targetPort: 21100
