#
# k8s-cms
# Kubernetes Intergration
# CMS Logging Service
#

apiVersion: v1
kind: Service
metadata:
  name: cms-logging
  labels:
    app: k8s-cms
    component: logging
spec:
  type: ClusterIP
  selector:
    app: k8s-cms
    component: logging
  ports:
    - name: cmsres
      port: 29000
      targetPort: 29000

