#
# k8s-cms
# Github Actions: CI pipeline
#

name: ci-pipeline
on: [ push, pull_request ]
env:
  # container build args
  VERSION: latest
  N_CONCURRENT: 12
  TAG_PREFIX: mrzzy

jobs:
  ## containers - builds & test k8s-cms containers
  # build cms containers
  build-cms-base:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build Containers"
        run: |
          make -j ${N_CONCURRENT}
          make export
          df -h
          free -h
      - uses: actions/upload-artifact@v1
        with:
          name: containers
          path: build/containers
  # tests containers run using the docker compose setup without exiting
  test-docker-compose-up:
    runs-on: ubuntu-18.04
    needs: [ build-containers ]
    steps:
     - uses: actions/checkout@v2
       with:
         submodules: recursive
     - uses: actions/download-artifact@v1
       with:
         name: containers
         path: build

     # tests containers run by running the docker-compose
     # stack and making sure none of them exit unexpectly
     - name: "Test Docker Compose up"
       env:
         CMS_SECRET_KEY: 4438f6c37f3b6401980d90b0bf06fd03
         KCMS_MASTER_JWT_KEY: 5wBVNc3Ltch8Ygj4FKaGPChqgkmx3JEH
         POSTGRES_USER: cmsuser
         POSTGRES_PASSWORD: YWaEjprTaRn3XGKuf5K3oB4vmVUrtCvh
         CMS_ADMIN_USER: admin
         CMS_ADMIN_PASSWORD: admin
         CMS_RANKING_USER: ranking
         CMS_RANKING_PASSWORD: ranking
       run: |
         make load -j ${N_CONCURRENT}
         timeout --preserve-status -sTERM 30s docker-compose up --abort-on-container-exit --no-build

  ## helm chart
  # lints helm chart
  lint-helm-chart:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: "Pull dependencies"
        run: |
          # pull helm
          curl -fsSL  https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3  | bash -
      - name: "Lint Helm chart"
        run: |
          helm lint chart
