#
# k8s-cms
# Github Actions: Containers
#

name: Containers
on: [ push, pull_request ]
env:
  # build args
  VERSION: latest
  N_CONCURRENT: 12
  TAG_PREFIX: mrzzy
  # testing dotenv
  CMS_SECRET_KEY: 4438f6c37f3b6401980d90b0bf06fd03
  KCMS_MASTER_JWT_KEY: 5wBVNc3Ltch8Ygj4FKaGPChqgkmx3JEH
  POSTGRES_USER: cmsuser
  POSTGRES_PASSWORD: YWaEjprTaRn3XGKuf5K3oB4vmVUrtCvh
  CMS_ADMIN_USER: admin
  CMS_ADMIN_PASSWORD: oJfU8UGdoLJNr2dED9yW2aQj
  CMS_RANKING_USER: ranking
  CMS_RANKING_PASSWORD: V4nRutupimVgn6F7B7WeUCzjRZGQOGK


jobs:
  # builds k8s-cms docker containers
  build-cms-db:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build CMS DB Image"
        run: |
          make $TAG_PREFIX/cms-db
          make export/$TAG_PREFIX/cms-db
      - uses: actions/upload-artifact@v1
        with:
          name: cms-db
          path: build/containers/cms-db.tar
      
  build-cms-base:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build CMS Base Image"
        run: |
          make $TAG_PREFIX/cms-base
          make export/$TAG_PREFIX/cms-base
      - uses: actions/upload-artifact@v1
        with:
          name: cms-base
          path: build/containers/cms-base.tar
      
  build-cms-checker:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS checker Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-checker
          make export/$TAG_PREFIX/cms-checker
      - uses: actions/upload-artifact@v1
        with:
          name: cms-checker
          path: build/containers/cms-checker.tar
      
  build-cms-evaluation:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS evaluation Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-evaluation
          make export/$TAG_PREFIX/cms-evaluation
      - uses: actions/upload-artifact@v1
        with:
          name: cms-evaluation
          path: build/containers/cms-evaluation.tar
      
  build-cms-log:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS log Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-log
          make export/$TAG_PREFIX/cms-log
      - uses: actions/upload-artifact@v1
        with:
          name: cms-log
          path: build/containers/cms-log.tar

  build-cms-printing:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS printing Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-printing
          make export/$TAG_PREFIX/cms-printing
      - uses: actions/upload-artifact@v1
        with:
          name: cms-printing
          path: build/containers/cms-printing.tar

  build-cms-proxy:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS proxy Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-proxy
          make export/$TAG_PREFIX/cms-proxy
      - uses: actions/upload-artifact@v1
        with:
          name: cms-proxy
          path: build/containers/cms-proxy.tar
      
  build-cms-resource:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS resource Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-resource
          make export/$TAG_PREFIX/cms-resource
      - uses: actions/upload-artifact@v1
        with:
          name: cms-resource
          path: build/containers/cms-resource.tar
      
  build-cms-scoring:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS scoring Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-scoring
          make export/$TAG_PREFIX/cms-scoring
      - uses: actions/upload-artifact@v1
        with:
          name: cms-scoring
          path: build/containers/cms-scoring.tar
      
  build-cms-web-admin:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS admin frontend Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-web-admin
          make export/$TAG_PREFIX/cms-web-admin
      - uses: actions/upload-artifact@v1
        with:
          name: cms-web-admin
          path: build/containers/cms-web-admin.tar

  build-cms-web-contest:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS contest frontend Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-web-contest
          make export/$TAG_PREFIX/cms-web-contest
      - uses: actions/upload-artifact@v1
        with:
          name: cms-web-contest
          path: build/containers/cms-web-contest.tar

  build-cms-web-ranking:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS ranking frontend Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-web-ranking
          make export/$TAG_PREFIX/cms-web-ranking
      - uses: actions/upload-artifact@v1
        with:
          name: cms-web-ranking
          path: build/containers/cms-web-ranking.tar
    
  build-cms-worker:
    needs: build-cms-base
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - name: "Build CMS worker Image"
        run: |
          make load/$TAG_PREFIX/cms-base
          make $TAG_PREFIX/cms-worker
          make export/$TAG_PREFIX/cms-worker
      - uses: actions/upload-artifact@v1
        with:
          name: cms-worker
          path: build/containers/cms-worker.tar

  build-kcms-master:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build k8s-cms master Image"
        run: |
          make $TAG_PREFIX/k8s-cms-master
          make export/$TAG_PREFIX/k8s-cms-master
      - uses: actions/upload-artifact@v1
        with:
          name: k8s-cms-master
          path: build/containers/k8s-cms-master.tar
  
  test-containers:
    runs-on: ubuntu-18.04
    needs:
      - build-cms-db
      - build-cms-base
      - build-cms-checker
      - build-cms-evaluation
      - build-cms-log
      - build-cms-printing
      - build-cms-proxy
      - build-cms-resource
      - build-cms-scoring
      - build-cms-web-admin
      - build-cms-web-contest
      - build-cms-web-ranking
      - build-cms-worker
      - build-kcms-master
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v1
        with:
          name: cms-db
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-base
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-checker
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-evaluation
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-log
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-printing
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-proxy
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-resource
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-scoring
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-web-admin
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-web-contest
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-web-ranking
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: cms-worker
          path: build/containers
      - uses: actions/download-artifact@v1
        with:
          name: kcms-master
          path: build/containers
      # tests containers run by running the docker-compose
      # stack and making sure none of them exit unexpectly
      - name: "Test Containers Run"
        run: |
          make load
          timeout --preserve-status -sTERM 30s docker-compose up --abort-on-container-exit --no-build
